Конфигурация для Hibernate, docker-compose, тестовый пример
hhru-school/checkup-extension pull request #10
Opened 2023-04-07 12:25 UTC by epolevikov

- добавил конфигурацию для Hibernate и простой пример Resource - Service - Dao.
- настроил docker-compose

2023-04-08 10:31 UTC, SAKorney commented
Обрати, пожалуйста, внимание на два момента указанных момента

2023-04-08 10:33 UTC, SAKorney requested changes

2023-04-08 10:33 UTC, SAKorney commented on backend/pom.xml
> +            <artifactId>spring-orm</artifactId>
Уточни эту зависимость у Саши

2023-04-08 10:33 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/config/JerseyConfig.java
> +public class JerseyConfig {
Ок. Пусть будет дело вкуса

2023-04-08 10:33 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Класс рассчитывался как единая точка внедерения зависимостей. Таким образом, получаем единое место где внедряем все зависимости + легко сможем программировать на уровне интерфейсов.

 Разносить Bean по разным файлам для зависимостей БД и настройки Jersey более-менее. Все остальные внедрения зависимостей (особенно бизнес логики) всё же предлагаю держать в одном месте.  Т.е. вернуть этот файл.

Узнаем мнения ещё Сергей и по возможности Саши.

2023-04-08 19:19 UTC, epolevikov commented on backend/pom.xml
> +            <artifactId>spring-orm</artifactId>
что именно уточнить? зачем?

2023-04-08 19:25 UTC, epolevikov commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
тут не совсем понял, о чем речь. Можешь привести конкретный пример, как именно ты хочешь использовать этот класс и какую проблему решить?

2023-04-08 19:33 UTC, SAKorney commented on backend/pom.xml
> +            <artifactId>spring-orm</artifactId>
Когда спрашивал у Саши о Transactional, он так же подтвердил, что достаточно подключить spring-tx. Вопрос здесь в том, чтобы не использовать технологии, которые усложнят после перевод на NaB.

2023-04-08 19:39 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Я о DI. Можно будет подставлять разные реализации централизовано. Подход с component не гибкий в этом плане. Условно  есть некий интерфейс (тип interface в  java) и его реализация, а нужно проверить новую реализацию. Всё что нужно будет сделать это заменить в соответствующем bean'е возвращаемую реализацию.

2023-04-09 10:44 UTC, epolevikov commented on backend/pom.xml
> +            <artifactId>spring-orm</artifactId>
помимо spring-tx нам нужно ещё пару зависимостей, чтобы подружить spring и хибер, они как раз внутри spring-orm живут. Глянь последние три импорта в конфиге для хибера.

2023-04-09 10:46 UTC, epolevikov commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
ок, я понял о чем ты, но пока не понял, зачем. Можешь привести конкретный пример, где такое нужно будет поиспользовать?

2023-04-09 10:52 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Из первого, что приходит: уровень доступа к данным (для отладки порою удобно переключиться с БД на работу в памяти) и переход на очереди.
Самое основное, что все зависимости будут внедряться в одном файле, чтобы потом не искать.

2023-04-09 10:53 UTC, SAKorney commented on backend/pom.xml
> +            <artifactId>spring-orm</artifactId>
Окей

2023-04-09 16:12 UTC, epolevikov commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
всё, что тебе нужно для отладки, лучше держать локально и не пушить в основную репу. Очереди нам не понадобятся, у нас mvp. Предлагаю ничего не усложнять и для внедрения зависимостей везде использовать `@Inject`, для нашего проекта этого будет более чем достаточно.

2023-04-09 18:53 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Полное понимание не достигнуто. Ждём ещё одно мнение.

2023-04-10 08:21 UTC, romanphilipskikh commented
@alexandrkrasovsky test

2023-04-10 10:24 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Коллеги, добрый день! Я пересмотрел момент на лекции спринга, погуглил и постарался собрать третье мнение. Как мне кажится ваши взгляды экспертнее моего и оба решения имеют свои плюсы, оба решения рабочии, но я постараюсь написать тезисы которые разрешат вопрос.

Spring Framework предоставляет множество способов реализации DI, одним из которых является использование аннотаций, таких как @Component, @Autowired и @Inject.

Если мы используем ComponentScan в вашем проекте, то мы можем просто навесить на бины @Component и инжектить их куда нужно с помощью @Inject. Не нужно усложнять процесс и создавать дополнительные конфигурационные файлы. Просто давайте использовать простые и удобные аннотации для внедрения зависимостей.

Один из вариантов использования DI в Spring Framework - это использование аннотации @Component, которая помечает класс как компонент, управляемый Spring. Классы, помеченные аннотацией @Component, будут автоматически сканироваться Spring и будут доступны для DI в других классах. Аннотация @Autowired или @Inject может использоваться для инжекции зависимостей.

В нашем случае, когда мы используем ComponentScan, нам не нужно создавать отдельный файл конфигурации для связывания зависимостей. Spring будет сканировать все классы, помеченные аннотацией @Component, и автоматически внедрять зависимости.

Если мы хотим создать несколько реализаций одного интерфейса и выбирать между ними в зависимости от ситуации, можно использовать аннотацию @Qualifier. Она позволяет явно указывать, какую реализацию интерфейса использовать в данном контексте.

Если мы хотим переключаться между различными реализациями интерфейсов, мы можем использовать файлы конфигурации, такие как XML-конфигурация или Java-конфигурация. В этом случае нам нужно будет явно связать зависимости, используя соответствующие теги или методы.

В целом, проект у нас небольшой и использование @Component и @Inject является более простым и удобным способом.

Как я понимаю вы еще задавали этот вопрос коллегам из hh, что они думают на этот счет? Я бы постарался не усложнять решение, но я не могу сказать какое решение будет правильным из-за отсутствия опыта в разработке.

2023-04-10 10:51 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Я против ComponentScan:
1. Внедрение зависимостей распыляется на весь проект
2. Замена зависимости становится накладной - либо комментить , либо использовать Qualifier.

Из опыта разработки принцип "Явное лучше неявного" всегда экономит ресурсы на неё.

Файл с классом настроек я создал. Оставалось дописывать по мере необходимости методы для внедрения нужной зависимости. Доводы почему это следует сделать я приводил ранее.

Поскольку мы работаем в команде. Если ответите в чём принципиальная сложность между отмечать @ Component/@ Inject и прописать один метод, я соглашусь, что это не нужно.

2023-04-10 11:03 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
@alexandrkrasovsky, поделись мнением

2023-04-10 11:18 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Я не против того или другого подхода. Для меня что тот, что другой - новый и непонятный опыт. Я выделю плюсы и минусы обоих для анализа. Дополните или исправьте пожалуйста.

ComponentScan:
Плюсы:
-Автоматическое сканирование классов и внедрение зависимостей может упростить код и сократить время разработки.
-Меньше кода нужно написать, т.к. не нужно прописывать каждую зависимость вручную.
Минусы:
-Сканирование может быть достаточно ресурсоемким, особенно в больших проектах.
-Внедрение зависимостей может быть распылено на весь проект, что усложняет обслуживание и поддержку кода.
-Замена зависимости может быть накладной, если она используется во многих местах, потому что нужно использовать Qualifier.

Явное внедрение зависимостей с помощью метода:
Плюсы:
-Внедрение зависимостей происходит явно и понятно для разработчика.
-Можно контролировать, какие зависимости используются в каких частях проекта.
-Легко заменять зависимости, так как они внедряются явно и только в тех местах, где они действительно нужны.
Минусы:
-Нужно писать больше кода, чтобы внедрить зависимости.
-Если в проекте много зависимостей, код может стать довольно громоздким.

Конечная цель использования ComponentScan и явного внедрения зависимостей с помощью метода одна и та же. Каждый подход имеет свои плюсы и минусы. У нас не очень большой проект и я думаю итоговый выбор не слишком критичен и может быть зависим от выших предпочтений. Но опять же, моя оценка проекта может быть неправильной. Как я понимаю в нашем проекте с обоими подходами не должно быть серьезных проблем.

2023-04-10 13:35 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/configuration/AppConfiguration.java
Хорошие аргументы с обеих сторон)
В хх мы не используем ComponentScan, поэтому рекомендую оставить историю с отдельным конфиг классом.
Аргументы почему мы используем ComponentScan вы как раз привели очень валидные. Еще к ним добавлю, что у часто такие конфиги не всеобъемлющие, а например разделяются в зависимости от доменных областей, или же на технические области (например конфиг дебага, конфиг логгирования). Таким образом конфиг сервиса представляется собой такую древовидную структуру вложенных конфигов.  Такое довольно сложно реализовать с помощью компонент скана
Сейчас думаю не нужно париться с таким разделением, но подход стоит оставить

2023-04-12 08:21 UTC, alexandrkrasovsky reviewed
CheckupInteraction, CheckupApiStub
Это что то связанное с авторизацией?

2023-04-12 08:21 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/utils/exception/AuthorizedException.java
> +public class AuthorizedException extends Exception {
Лучше экстендиться от RuntimeException. 
1) не надо прокидывать в методах
2) не надо обрабатывать в try-catch
3) Такого рода эксепшены, как AuthorizedException (пользователь не авторизован), ЧтоТоТамNotFoundException хорошо мапятся на http статус коды
Поэтому такие эксепшены можно кинуть где то в сервисе, и забить на него, он смаппится в нужный статус код
Можно сконфигурить например вот так
https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice

2023-04-12 14:54 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/utils/exception/AuthorizedException.java
> +public class AuthorizedException extends Exception {
Подскажи, пожалуйста, какую зависимость нужно указать в pom-файле для ResponseEntityExceptionHandler?

2023-04-12 14:54 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/test/TestDao.java
> +    private final TransactionHelper transactionHelper;
Разобрался. После следующего коммита заработает)

2023-04-12 14:58 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/ContestApiResource.java
> +            throw new NotFoundException();
Если скрывать по примеру того же GitHub? Возможно, мы хотим, чтобы пользователь знал о такой ручке

2023-04-12 15:08 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/utils/exception/AuthorizedException.java
> +public class AuthorizedException extends Exception {
Ещё вариант делать через jakarta.ws.rs.ext.ExceptionMapper

2023-04-13 06:06 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/core/ContestApiResource.java
> +            throw new NotFoundException();
Если такой логикой обосновано, то ок

2023-04-13 06:09 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/utils/exception/AuthorizedException.java
> +public class AuthorizedException extends Exception {
Да, даже лучше с jakarta.ws.rs.ext.ExceptionMapper

2023-04-13 17:43 UTC, SAKorney approved these changes

2023-04-13 17:55 UTC, serjbetoni approved these changes

2023-04-13 17:58 UTC, merged