added Entity and Dto, Controller, Service RequestDto for Entity also added dependency in POM
hhru-school/checkup-extension pull request #14
Opened 2023-04-16 15:41 UTC by serjbetoni

Начальная заготовка по сущностям - Problem, Submission, Verification. Также Dto, Controller, Service RequestDto для этих сущностей

2023-04-17 09:37 UTC, SAKorney requested changes
Общие моменты:
1. Не использовать Spring Data;
2. Не использовать ComponentScan (RestController и Repository).

Общие рекомендации для подумать/исправить:
1. Устранить несоответствия из первой секции;
2. Пакет Data планировался как уровень доступа к данным. Сейчас получился набор микросервисов.Возможно, пока предпочтительно будет убрать все классы Service и Repository из Data до тех пор пока не определимся с публичным API.

Из мелочей, проверь, чтобы все файлы оканчивались пустой строкой.

Похвальная, хорошая продуктивность.

2023-04-17 09:37 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/controller/ProblemController.java
> +@RequestMapping("/api/problems")
Есть договорённость использовать Jersey вместо SpringMVC

2023-04-17 09:37 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/controller/ProblemController.java
> +@RestController
RestController это автоматического разрешения зависимостей. Вместо этого нужно прописывать все зависимости в классе AppConfiguration через аннотацию import или метод, аннотированный c Bean (если требуется передать параметры создания)

2023-04-17 09:37 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/entity/Problem.java
> +  private String type;
Лучше сразу заложить, что это будет цифровой код. Хватит типа byte.

2023-04-17 09:37 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/entity/Problem.java
> +  private Integer maxAttempts;
int выглядит слишком большим для количества попыток. Хватит short или даже byte. Вряд ли их будет больше 100

2023-04-17 09:37 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException {
Перенести в пакет ru.hh.school.checkupextension.utils.exception или ru.hh.school.checkupextension.utils.exception.data

2023-04-18 11:08 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/exception/ResourceNotFoundException.java
> +  public static final String PROBLEM_ID_NOT_FOUND_MESSAGE = "Problem not found with id: %s";
Неуспеваю исправить наверно сейчас, есть предложение исправить позже если проблема станет более очевидна

2023-04-18 11:52 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/exception/ResourceNotFoundException.java
> +  public static final String PROBLEM_ID_NOT_FOUND_MESSAGE = "Problem not found with id: %s";
Да, ты прав, нужно разделить. Поправил

2023-04-18 12:26 UTC, SAKorney commented
Сойдёмся на следующем:
1. Переименовать [Name]Controller в [Name]Resource
2. Заменить  тип поля для DAO с типа реализации на интерфейс
и я подтвержу

2023-04-18 12:40 UTC, SAKorney approved these changes
Следующий шаг будет рефакторинг

2023-04-18 12:40 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/service/ProblemService.java
> +  private final ProblemDaoImpl problemDao;
Нет смысла вводить интерфейс, если поля имеют тип реализации

2023-04-18 12:40 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/request/ProblemRequestDto.java
> +  private byte type;
У DTO тип будет скорее всего текстовым. Либо нужно отдельно передавать на frontend словарь, чтобы на стороне клиента переводить код в текст

2023-04-18 12:42 UTC, merged