implement admin main page
hhru-school/checkup-extension pull request #15
Opened 2023-04-16 16:05 UTC by rmunirov

#13 
1. Добавлена верстка 3-х табов для страницы пользователя с правами администратора:
- Испытания
- Задачи
- Результаты
2. Примеры:
![image](https://user-images.githubusercontent.com/42567523/232325350-60455948-2ab5-4a7a-90f3-ea15385b92a5.png)
![image](https://user-images.githubusercontent.com/42567523/232325375-6e7bd068-5879-4f59-a852-9a4ae84700f6.png)
![image](https://user-images.githubusercontent.com/42567523/232325403-ca0aa245-7352-4b39-afbf-0a87d49dc668.png)

2023-04-17 09:20 UTC, romanphilipskikh requested changes

2023-04-17 09:20 UTC, romanphilipskikh commented on frontend/public/locales/ru/translation.json
>      "button.sent": "Отправить",
Пустую строчку в конце каждого файла не забывай, много где нет

2023-04-17 09:20 UTC, romanphilipskikh commented on frontend/src/__data__/slices/index.ts
>    type: "js" | "html";
Enum для типа может давай? Кажется это много где будет юзаться.

2023-04-17 09:20 UTC, romanphilipskikh commented on frontend/src/__data__/slices/index.ts
>    status: "process" | "error";
Тоже енам

2023-04-17 09:20 UTC, romanphilipskikh commented on frontend/src/pages/index-page/index.tsx
> +  const [mode, setMode] = useState<"admin" | "user">("admin");
mode наверное не нужно ставить в дефолт никакой, сейчас может и норм так оставить, но в будущем даавай если mode никакой не пришел, то рисуем ошибку

2023-04-17 17:08 UTC, rmunirov commented on frontend/public/locales/ru/translation.json
>      "button.sent": "Отправить",
Ок, принял, вроде стараюсь везде проходить prettier-ом, похоже упустил

2023-04-17 17:09 UTC, rmunirov commented on frontend/src/__data__/slices/index.ts
>    type: "js" | "html";
Да, в будущем планировал добавить, сейчас больше времени верстке уделял.

2023-04-17 17:10 UTC, rmunirov commented on frontend/src/pages/index-page/index.tsx
> +  const [mode, setMode] = useState<"admin" | "user">("admin");
Это сделал только для теста, чтобы можно было менять режим отображения наглядно, в будущем удалится.

2023-04-19 17:14 UTC, rmunirov commented on frontend/src/pages/index-page/index.tsx
> +  const [mode, setMode] = useState<"admin" | "user">("admin");
Тут наверное когда приходит токен, делаем запрос в бэк, он нам отдает данные по пользователю, в т.ч. его роль

2023-04-24 16:22 UTC, merged