Added api for problem entity and postman-collection. Changed init.sql
hhru-school/checkup-extension pull request #26
Opened 2023-05-14 08:06 UTC by serjbetoni

работа еще ведется, сервер дает ошибку

2023-05-18 14:41 UTC, SAKorney requested changes

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<Problem> getAllProblems() {
Метод возвращает список сущностей, вместо списка dto.
Другой более важный момент, что для API поступления не нужен метод получения всех задач. Это актуально только для администрирования. Я за то, чтобы убрать этот метод из ContestService и ContestResurce.

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public void deleteProblem(@PathParam("id") long id) {
Удаление прерогатива администратора. Точно удалить из ContestService и ContestResource.

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestService.java
> +  public List<Problem> getAllProblems() {
Удалить. (См. причину выше)

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestService.java
> +  public void deleteProblem(long id) {
Удалить. (См. причину выше)

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  @Path("task/{problem_id}")
Поскольку договорились на Problem, заменить на problem.

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public ContestProblemDto createProblem(@Valid Problem problem) {
Создание задачи на администраторе. Здесь этот метод неуместен. Удалить.

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public ContestProblemDto updateProblem(@PathParam("id") long id, Problem problem) {
Аналогично "Созданию". Удалить.

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestService.java
> +  public ContestProblemDto createProblem(Problem problem) {
Удалить. (См. причину выше)

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestService.java
> +  public ContestProblemDto updateProblem(long id, Problem problem) {
Удалить. (См. причину выше)

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/entity/Problem.java
> +  public static class Template implements Serializable {
На твоё усмотрение. Работает и без "implements Serializable"

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/entity/Problem.java
>  public class Problem {
Нужен атрибут (OneToMany) ссылающийся на проверки (Verification)

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/repository/ProblemRepository.java
> +    return getSession().createQuery("SELECT p FROM ru.hh.school.checkupextension.core.data.entity.Problem p",
Достаточно указать Problem без полного пути

2023-05-18 14:41 UTC, SAKorney commented on checkup-extension.postman_collection.json
> +}
Добавить пустую строчку в  конец файла

2023-05-18 14:41 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/dto/contest/ContestProblemDto.java
> +  public final byte type;
Должно быть строковое представление, вместо числового кода. По примеру  с преобразованием в SubmissionMapper с помощью  SubmissionsStatus

2023-05-19 07:26 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<Problem> getAllProblems() {
Пока что удалил, в следующих ПРах перенесу в Админ часть и изменю тип объектов в листе

2023-05-19 07:26 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestService.java
> +  public List<Problem> getAllProblems() {
Пока что удалил, в следующих ПРах перенесу в Админ часть

2023-05-19 07:26 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestService.java
> +  public void deleteProblem(long id) {
Пока что удалил, в следующих ПРах перенесу в Админ часть

2023-05-19 07:26 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/entity/Problem.java
> +  public static class Template implements Serializable {
Убрал интерфейс

2023-05-19 07:27 UTC, serjbetoni commented on backend/src/main/java/ru/hh/school/checkupextension/core/repository/ProblemRepository.java
> +    return getSession().createQuery("SELECT p FROM ru.hh.school.checkupextension.core.data.entity.Problem p",
Понимаю, почему-то IDE ругалась без полного пути, не могла найти класс, хотя импортировалось корректно

2023-05-19 09:34 UTC, SAKorney requested changes

2023-05-19 09:34 UTC, SAKorney commented on backend/db/init.sql
> -    problem_id serial primary key,
Правило наименования идентификаторов в БД: название сущности_id. Вернуть как было

2023-05-19 09:34 UTC, SAKorney commented on backend/db/init.sql
> -        REFERENCES problem(problem_id)
см. выше

2023-05-19 09:34 UTC, SAKorney commented on backend/db/init.sql
> -        REFERENCES problem(problem_id)
см. выше

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminResource.java
> -@Path("/admin")
Вернуть как было, иначе будут проблемы с адресацией запросов

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminResource.java
> +  public ContestProblemDto createProblem(@Valid Problem problem) {
Этот функционал уже был реализован. Убрать и вернуть createNewProblem.

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminResource.java
> -  public EditableProblemDto createNewProblem(
Вернуть (см. выше). Функционал обновления реализовывать отдельной задачей, чтобы избежать больших ПР

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminService.java
> +  public ContestProblemDto createProblem(Problem problem) {
Удалить

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminService.java
> +  public ContestProblemDto updateProblem(long id, Problem problem) {
Удалить

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/enums/ProblemType.java
> +    CHECKED((byte) 0),
Это состояние задачи. Тип задачи: JavaScript или HTML. Исправить весь enum в соответствии с двумя типами задач.

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/repository/ProblemRepository.java
> +  public Problem create(Problem problem) {
Какая цель перегрузки? Чем не подошла существующая реализация?

2023-05-19 09:34 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/utils/constant/ProblemJsonPropertyName.java
> +public class ProblemJsonPropertyName {
Дублирует ProblemDtoJsonPropertyName. Дополнить и использовать его. ProblemJsonPropertyName удалить.

2023-05-19 10:35 UTC, SAKorney approved these changes

2023-05-19 10:36 UTC, merged