Task creation API
hhru-school/checkup-extension pull request #28
Opened 2023-05-16 18:45 UTC by SAKorney

Добавлен метод для создания новых задач. Предоставлен API.
Пока в общем виде без преобразований сущностей в DTO, поскольку сущность задач ещё дорабатыывается.

2023-05-17 07:42 UTC, alexandrkrasovsky requested changes
Все ок, у меня вопросики опять только к неймингу.
Я может что то не понимаю, но почему EditableTaskDto маппится в Problem? Почему не EditableProblemDto? 
Если нравится таск, то пусть будет везде таск, или везде проблем. Это ведь одно и то же?
И еще почему editable? Еще будет такая же нередактируемая?

И тест выглядит больше как AdminServiceTest.


Как по мне нейминг очень важная часть. Хочется НЕ читая код понимать что он делает из названия метода, сервиса и т.д.
Когда одинаковые штуки в разных формах (entity, dto) называются по разному это тоже вызывает проблемы при чтении кода. Т.к. думаешь что это разные вещи из разных бизнес контекстов

2023-05-17 07:42 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminService.java
> +    if (!user.isAdmin())
ifы без фигурных скобок - зло
Например захочешь еще добавить запись в лог и одна из строк уедет из под if, будут баги

2023-05-17 13:58 UTC, SAKorney commented
Принято решение использовать название Problem

2023-05-17 14:20 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/dto/admin/EditableProblemDto.java
> +      @JsonProperty(TaskDtoJsonPropertyName.ID) long taskId,
problemId

2023-05-17 14:21 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/utils/constant/TaskDtoJsonPropertyName.java
> +public class TaskDtoJsonPropertyName {
Да, спасибо

2023-05-18 07:50 UTC, alexandrkrasovsky approved these changes

2023-05-18 07:51 UTC, alexandrkrasovsky approved these changes

2023-05-18 07:52 UTC, alexandrkrasovsky approved these changes

2023-05-18 11:32 UTC, merged