Feature/all added problems handle
hhru-school/checkup-extension pull request #56
Opened 2023-06-06 13:06 UTC by SAKorney

Добавлена постраничная выдача списка существующих задач, доступных для редактирования.

Основные изменения в файлах AdminResource.java, AdminService.java, ProblemRepository.java и EditableProblemDto.java.

Дополнительно в рамках поддержания чистоты кода, перегрупированы импорты и порядок определения методов.

2023-06-06 14:52 UTC, alexandrkrasovsky requested changes
Еще насчет пагинации. Наверняка фронту захочется узнать, а сколько же там всего таких элементов, чтоб нарисовать список страниц для навигации или же чтоб понять когда переставать запрашивать новые страницы

2023-06-06 16:58 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/admin/AdminResource.java
> +  public List<EditableProblemInfoDto> getAllProblems(
Добавил новую dto содержащую информацию о текущем состоянии пагинации

2023-06-06 17:02 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<ContestProblemInfoDto> getContestProblemsInfo() {
Здесь технически добавить можно. Другое дело, что этот список обозримого размера (2-3 задачи, которые будут предложены к решению пользователю) и пока добавлять, чтобы было, выглядит как усложнение на данном этапе. Тем более, сейчас я ввёл универсальный механизм для возврата состояния пагинации, который позволит легко расширить функционал в дальнейшем при необходимости.

2023-06-07 09:05 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<ContestProblemInfoDto> getContestProblemsInfo() {
Все верно. Подумай как будет все это выкатываться на работающий прод, с учетом того, что фронт тоже придется менять в случае чего. Например тут захотим тоже пагинацию сделать

2023-06-07 09:08 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/dto/PaginationResultDto.java
> +      @JsonProperty("total") long totalRecords,
Я бы пока оставил только totalRecords, но так тоже норм

2023-06-07 09:08 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/dto/PaginationResultDto.java
> +      @JsonProperty("total") long totalRecords,
totalPages и totalRecords кажется дублируют друг друга

2023-06-07 09:10 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/utils/PaginationResult.java
> +public record PaginationResult<T>(int currentPage, int pageSize, int totalPages, long totalRecords, List<T> records) {
Нужна ли она тебе не в рамках респонса?

2023-06-07 09:18 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<ContestProblemInfoDto> getContestProblemsInfo() {
В том плане, что замена List<ContestProblemInfoDto> на  PaginationResultDto<ContestProblemInfoDto> в дальнейшем будет накладно? С другой стороны, фронт ведь все равно придётся менять

2023-06-07 09:19 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/dto/PaginationResultDto.java
> +      @JsonProperty("total") long totalRecords,
totalRecords - количество записей в БД. totalPages соответствуют количеству  страниц при имеющемся количестве записей (totalRecords) и заданном размере страницы (pageSize). Чтобы не загружать frontend принял решение сразу вычислять это значение

2023-06-07 09:22 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/core/data/utils/PaginationResult.java
> +public record PaginationResult<T>(int currentPage, int pageSize, int totalPages, long totalRecords, List<T> records) {
Когда писал этот код, было желание отделаться одним классом, который и на уровне доступа данных и на уровне endpoint'а. Победил педантизм и теоретическая гибкость

2023-06-07 09:23 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<ContestProblemInfoDto> getContestProblemsInfo() {
Или о том, чтобы возвращать абстрактный Response?

2023-06-07 09:28 UTC, alexandrkrasovsky commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<ContestProblemInfoDto> getContestProblemsInfo() {
сейчас отдается вот такой json [{}, {}]
если надо будет что то добавить кроме листа, то придется добавить объект контейнер, json будет такой 
{ list: [{}, {}], novayaInfa: {}}
Теперь на проде, чтоб перейти из варианта 1 в вариант 2 ты не можешь просто поменять респонс, тк фронт ждет старый формат. Тебе нужно сделать новую ручку - выпустить бек, пересадить фронт на новую ручку, удалить старую.

Это пример почему стоит делать обертки над стандартными типами

2023-06-07 16:21 UTC, SAKorney commented on backend/src/main/java/ru/hh/school/checkupextension/contest/ContestResource.java
> +  public List<ContestProblemInfoDto> getContestProblemsInfo() {
Добавил класс-обёртку ContestDto в коммите, с неприличным из-за опечатки названием

2023-06-08 07:11 UTC, alexandrkrasovsky approved these changes

2023-06-08 07:18 UTC, merged